### ISSUE TITLE
Which transformation is implemented here?

### ISSUE THREAD

**Issue by adrianloy** [HPI-DeepLearning/DIRNet#1]
Hi,
Just a short question: Which transformation is implemented in this DIRnet? Is it a cubic B spline transformation as described in "[Nonrigid Registration Using Free-Form
Deformations: Application to Breast MR Images](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.126.4732&rep=rep1&type=pdf)"   (Section II B) and mentioned in the original DIRnet paper?

Thanks in advance, and nice code!
Cheers

**Comment by jfilter** [comment]
I think this is in the wrong repo.
