### ISSUE TITLE
Why doesnt Affine work?

### ISSUE THREAD

**Issue by ChrisBellew** [HPI-DeepLearning/DIRNet#2]
Hi :)

Firstly, thanks for letting other people use your code. If you have a moment, I would appreciate if you could answer the question..."Why did you stop using an affine transform?".

I noticed you added it and shortly after disabled it with use_Affine=False. I had the same line of thinking, that an affine transform is a useful way to describe the registration of an image to another. I have not experienced good results. Often the registration is poor, sometimes very poor.

Can you remember why you stopped using the affine transform? Maybe you have realised why it wont work?

Thanks! :)
Chris

**Comment by adrianloy** [comment]
It depends what your images look like. Affine transformation is limited in a way, that it can only "do stuff" on a global level: basically it can scale and/or rotate the whole image. If you need a transformation that changes something in only one area of the image to register them, this wont help much!

**Comment by ChrisBellew** [comment]
For my use case, the images are approximately rigid planar so an affine
transformation should work. Just wondered if there was a specific reason in
relation to this but I guess not, I'll keep trying.

Thanks for you help and quick response.

Chris

**Comment by adrianloy** [comment]
You are welcome. Good Luck!
