### ISSUE TITLE
How do you use patches to implement the registration?

### ISSUE THREAD

**Issue by Adengna** [HPI-DeepLearning/DIRNet#4]
Firstly, thanks a lot for sharing the code to us.
In the paper "End-to-End Unsupervised Deformable Image Registration with a Convolutional Neural Network", you explain that you use patches to implement the deformable image registration. While, I read your code, but I did not find the patches used in the code.

**Comment by adrianloy** [comment]
We are not associated with the authors of the paper. This was just a student project to implement it. I think the patches thing is simply a preprocessing step of the dataset, cutting bigger images into smaller patches. It wasnt needed for the data we worked with.
